//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""AlwaysActive"",
            ""id"": ""c15f0b14-dbe8-4c8c-9328-d63d74db7b02"",
            ""actions"": [
                {
                    ""name"": ""ToggleInventory"",
                    ""type"": ""Button"",
                    ""id"": ""8273c7d6-d5b3-4e57-ba72-52c83f1b684e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TogglePause"",
                    ""type"": ""Button"",
                    ""id"": ""ba8b4625-68f3-49af-8899-cd7ef76438b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item0"",
                    ""type"": ""Button"",
                    ""id"": ""86e2c0ad-92ae-4d4a-8b26-a6c812d2e83f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item1"",
                    ""type"": ""Button"",
                    ""id"": ""24f6a2f8-6ea1-4765-b713-799e8863bb79"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""fdd2f852-670b-4af6-acc9-701e610601e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDebug"",
                    ""type"": ""Button"",
                    ""id"": ""f0b3314d-7001-4a1e-9559-1c6becdf2245"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dfa220fc-fc43-4a82-88e8-eb46707b9736"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb5c3b72-c8a8-42ab-a56b-8eb1a936e299"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""685ecca6-fa9c-4311-91e1-c61a39b62a05"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TogglePause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2ff2ac7-36db-46b7-8857-01d31e70da48"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TogglePause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7db5e94f-a8f5-438e-b4d0-891f18cfbea8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e7dc8a5-39c5-48c5-a370-b43540474f3c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb6d638e-13c2-4845-bba8-15bdfeb35849"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2d74411-45f0-478f-bc8e-3ad65ef1c903"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57d4843a-51fa-4ae2-bb7d-498b485daed8"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a876e85-999e-46d7-86f8-dbf84a22be45"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10b7400f-ee3e-4964-91ca-6dd2441a8503"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDebug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f9ff4d5-22bc-45ca-9c19-704af136e9e5"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDebug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Grounded"",
            ""id"": ""2831f0b9-9a6d-429a-a4e7-58fde86a8733"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2fa00f88-7450-47c1-9b0b-695d224cd349"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": ""AxisDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sword"",
                    ""type"": ""Button"",
                    ""id"": ""29c1067b-0c2c-46b6-9212-2110bf4950b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shield"",
                    ""type"": ""Button"",
                    ""id"": ""876a3a0a-78ad-4a17-ac13-80f3ccf5d042"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""f251beb6-573d-4b4e-a517-b2513c54c2af"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9b368810-d735-4caf-87f8-6c82a3b1012d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""29561bd3-f321-4ab2-8830-f7bab97a89cf"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""00cb9c14-725c-418e-b9ea-7504f550c89c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""01a58f2b-81d1-4ec8-bb5c-33314a37da2b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c5ceb4f0-9833-4667-bffe-bba35a139edc"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7b921b8-8d85-4a6d-8394-53ec1343a07e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0617602-4463-4103-86c6-b9d1814e3931"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6014e9ce-0a86-49d9-8c39-83e22f7207f4"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a11aeba9-0b26-46e6-aea2-3a3094692ad0"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OnlyUI"",
            ""id"": ""c3f106f4-3dc7-4b30-9081-70860db59718"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""1c459a07-1b81-47ae-b00e-e603b072dba4"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Extra Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""37587d94-2673-48da-80b5-186da0d72b1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Item 0 And Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""a82f96de-8947-4b6b-8a97-bbd86446fda8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Item 1 And Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""3bc55ffa-bd74-44b1-b23d-3c9cf5000759"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Movement"",
                    ""type"": ""Value"",
                    ""id"": ""8cf85013-88c4-4ffb-a1dd-012da5f3464a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""74e57320-90e2-4dc0-922d-e2a2bfa2458b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9eca0f18-087b-483b-9a95-da9a6c3207c1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fdbf1e69-1782-4c32-8782-e33e954ce251"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4a866a0c-1f4a-4543-a34d-fe1fe84dd939"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ea0eacdb-f95d-4062-afcd-5d884a43cb1a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""89357bc8-e126-4af9-a563-4440f76096d8"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Cruceta"",
                    ""id"": ""17bfd072-9298-4539-8718-8955691c89b6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""81dccb4a-e92f-4120-b08d-fdba48e2c7df"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""16f3eaa4-7d1f-4f8b-8906-1926f803518c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5c7f9755-51ff-4a79-97f9-8ebf1c364312"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7fb19a2c-daa4-4484-91b1-4a4b147a4f76"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cbf24eb3-11e8-4576-bd67-c9156784bce7"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Extra Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""503e0a94-0816-427e-b40b-93fecb4306c0"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bccc34b-82cd-4aa0-bd3b-aadaa1a25298"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Item 0 And Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c8f0619-8d74-4ded-9cc8-41a03f7fc06e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Item 1 And Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu"",
            ""id"": ""85a2c2f6-2250-4a4f-ad62-2dbb5d6f7abf"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4372facc-9441-43b3-8108-202084545d28"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press"",
                    ""type"": ""Button"",
                    ""id"": ""79206ccd-3fcf-4002-9884-05d02d5f7ced"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMovement"",
                    ""type"": ""Value"",
                    ""id"": ""735d2d26-f5ac-406b-9784-61f138f2fd47"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AnyKey"",
                    ""type"": ""Button"",
                    ""id"": ""05ff38b0-1f5e-43a0-b2eb-8732549dd671"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b47f7eaa-17cf-4e2c-840a-11f721deda00"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""335ec98f-f996-4514-b100-e7520f075fa1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""043afd03-1f29-49fe-a579-5ebb533b22e8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b3b67f83-afa3-4b52-b336-cf592aa820d8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4f8fd0d1-1a6b-4e70-b0df-32fc847bd643"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9d6aa536-af21-4247-9410-92df5e4dc6a6"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector2"",
                    ""id"": ""ab3a456c-6e51-45d4-bff6-0e9d36607665"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cd664acf-9209-4c74-a951-31c03f5423d6"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ca8a4d89-f8fa-4743-965d-b2299714ca19"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1564231f-7ee6-49b5-98c5-6ada853fb659"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""72fed32d-e531-4aa3-b0e5-013fb5fc6a73"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1f1d2d85-da4e-49f0-8fec-e140966a2a83"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1974027-e891-4d9e-a15c-37def4631c43"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8beddddd-cfb3-411a-92e9-bfb57b195458"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2831ef26-97a5-42b7-a370-77c1a7e13f13"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f27066d0-f48b-4f8a-b87d-779474f73a22"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""508a06a4-7ce9-4f90-b7de-a0a4be6513d7"",
                    ""path"": ""<Gamepad>/*"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c6eb2da-d0fb-4a88-af16-0744c9fbf111"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""856a9d1a-3565-442e-ac7d-4d24b6ca10f5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c0248b3-a13f-4d27-8f5f-27e1c1b2d0f0"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AlwaysActive
        m_AlwaysActive = asset.FindActionMap("AlwaysActive", throwIfNotFound: true);
        m_AlwaysActive_ToggleInventory = m_AlwaysActive.FindAction("ToggleInventory", throwIfNotFound: true);
        m_AlwaysActive_TogglePause = m_AlwaysActive.FindAction("TogglePause", throwIfNotFound: true);
        m_AlwaysActive_Item0 = m_AlwaysActive.FindAction("Item0", throwIfNotFound: true);
        m_AlwaysActive_Item1 = m_AlwaysActive.FindAction("Item1", throwIfNotFound: true);
        m_AlwaysActive_Interact = m_AlwaysActive.FindAction("Interact", throwIfNotFound: true);
        m_AlwaysActive_ToggleDebug = m_AlwaysActive.FindAction("ToggleDebug", throwIfNotFound: true);
        // Grounded
        m_Grounded = asset.FindActionMap("Grounded", throwIfNotFound: true);
        m_Grounded_Movement = m_Grounded.FindAction("Movement", throwIfNotFound: true);
        m_Grounded_Sword = m_Grounded.FindAction("Sword", throwIfNotFound: true);
        m_Grounded_Shield = m_Grounded.FindAction("Shield", throwIfNotFound: true);
        // OnlyUI
        m_OnlyUI = asset.FindActionMap("OnlyUI", throwIfNotFound: true);
        m_OnlyUI_Movement = m_OnlyUI.FindAction("Movement", throwIfNotFound: true);
        m_OnlyUI_ExtraConfirm = m_OnlyUI.FindAction("Extra Confirm", throwIfNotFound: true);
        m_OnlyUI_MouseItem0AndConfirm = m_OnlyUI.FindAction("Mouse Item 0 And Confirm", throwIfNotFound: true);
        m_OnlyUI_MouseItem1AndConfirm = m_OnlyUI.FindAction("Mouse Item 1 And Confirm", throwIfNotFound: true);
        m_OnlyUI_MouseMovement = m_OnlyUI.FindAction("Mouse Movement", throwIfNotFound: true);
        // MainMenu
        m_MainMenu = asset.FindActionMap("MainMenu", throwIfNotFound: true);
        m_MainMenu_Movement = m_MainMenu.FindAction("Movement", throwIfNotFound: true);
        m_MainMenu_Press = m_MainMenu.FindAction("Press", throwIfNotFound: true);
        m_MainMenu_MouseMovement = m_MainMenu.FindAction("MouseMovement", throwIfNotFound: true);
        m_MainMenu_AnyKey = m_MainMenu.FindAction("AnyKey", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AlwaysActive
    private readonly InputActionMap m_AlwaysActive;
    private IAlwaysActiveActions m_AlwaysActiveActionsCallbackInterface;
    private readonly InputAction m_AlwaysActive_ToggleInventory;
    private readonly InputAction m_AlwaysActive_TogglePause;
    private readonly InputAction m_AlwaysActive_Item0;
    private readonly InputAction m_AlwaysActive_Item1;
    private readonly InputAction m_AlwaysActive_Interact;
    private readonly InputAction m_AlwaysActive_ToggleDebug;
    public struct AlwaysActiveActions
    {
        private @InputActions m_Wrapper;
        public AlwaysActiveActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleInventory => m_Wrapper.m_AlwaysActive_ToggleInventory;
        public InputAction @TogglePause => m_Wrapper.m_AlwaysActive_TogglePause;
        public InputAction @Item0 => m_Wrapper.m_AlwaysActive_Item0;
        public InputAction @Item1 => m_Wrapper.m_AlwaysActive_Item1;
        public InputAction @Interact => m_Wrapper.m_AlwaysActive_Interact;
        public InputAction @ToggleDebug => m_Wrapper.m_AlwaysActive_ToggleDebug;
        public InputActionMap Get() { return m_Wrapper.m_AlwaysActive; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AlwaysActiveActions set) { return set.Get(); }
        public void SetCallbacks(IAlwaysActiveActions instance)
        {
            if (m_Wrapper.m_AlwaysActiveActionsCallbackInterface != null)
            {
                @ToggleInventory.started -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnToggleInventory;
                @ToggleInventory.performed -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnToggleInventory;
                @ToggleInventory.canceled -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnToggleInventory;
                @TogglePause.started -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnTogglePause;
                @TogglePause.performed -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnTogglePause;
                @TogglePause.canceled -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnTogglePause;
                @Item0.started -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnItem0;
                @Item0.performed -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnItem0;
                @Item0.canceled -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnItem0;
                @Item1.started -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnItem1;
                @Item1.performed -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnItem1;
                @Item1.canceled -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnItem1;
                @Interact.started -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnInteract;
                @ToggleDebug.started -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnToggleDebug;
                @ToggleDebug.performed -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnToggleDebug;
                @ToggleDebug.canceled -= m_Wrapper.m_AlwaysActiveActionsCallbackInterface.OnToggleDebug;
            }
            m_Wrapper.m_AlwaysActiveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ToggleInventory.started += instance.OnToggleInventory;
                @ToggleInventory.performed += instance.OnToggleInventory;
                @ToggleInventory.canceled += instance.OnToggleInventory;
                @TogglePause.started += instance.OnTogglePause;
                @TogglePause.performed += instance.OnTogglePause;
                @TogglePause.canceled += instance.OnTogglePause;
                @Item0.started += instance.OnItem0;
                @Item0.performed += instance.OnItem0;
                @Item0.canceled += instance.OnItem0;
                @Item1.started += instance.OnItem1;
                @Item1.performed += instance.OnItem1;
                @Item1.canceled += instance.OnItem1;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @ToggleDebug.started += instance.OnToggleDebug;
                @ToggleDebug.performed += instance.OnToggleDebug;
                @ToggleDebug.canceled += instance.OnToggleDebug;
            }
        }
    }
    public AlwaysActiveActions @AlwaysActive => new AlwaysActiveActions(this);

    // Grounded
    private readonly InputActionMap m_Grounded;
    private IGroundedActions m_GroundedActionsCallbackInterface;
    private readonly InputAction m_Grounded_Movement;
    private readonly InputAction m_Grounded_Sword;
    private readonly InputAction m_Grounded_Shield;
    public struct GroundedActions
    {
        private @InputActions m_Wrapper;
        public GroundedActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Grounded_Movement;
        public InputAction @Sword => m_Wrapper.m_Grounded_Sword;
        public InputAction @Shield => m_Wrapper.m_Grounded_Shield;
        public InputActionMap Get() { return m_Wrapper.m_Grounded; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GroundedActions set) { return set.Get(); }
        public void SetCallbacks(IGroundedActions instance)
        {
            if (m_Wrapper.m_GroundedActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_GroundedActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_GroundedActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_GroundedActionsCallbackInterface.OnMovement;
                @Sword.started -= m_Wrapper.m_GroundedActionsCallbackInterface.OnSword;
                @Sword.performed -= m_Wrapper.m_GroundedActionsCallbackInterface.OnSword;
                @Sword.canceled -= m_Wrapper.m_GroundedActionsCallbackInterface.OnSword;
                @Shield.started -= m_Wrapper.m_GroundedActionsCallbackInterface.OnShield;
                @Shield.performed -= m_Wrapper.m_GroundedActionsCallbackInterface.OnShield;
                @Shield.canceled -= m_Wrapper.m_GroundedActionsCallbackInterface.OnShield;
            }
            m_Wrapper.m_GroundedActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Sword.started += instance.OnSword;
                @Sword.performed += instance.OnSword;
                @Sword.canceled += instance.OnSword;
                @Shield.started += instance.OnShield;
                @Shield.performed += instance.OnShield;
                @Shield.canceled += instance.OnShield;
            }
        }
    }
    public GroundedActions @Grounded => new GroundedActions(this);

    // OnlyUI
    private readonly InputActionMap m_OnlyUI;
    private IOnlyUIActions m_OnlyUIActionsCallbackInterface;
    private readonly InputAction m_OnlyUI_Movement;
    private readonly InputAction m_OnlyUI_ExtraConfirm;
    private readonly InputAction m_OnlyUI_MouseItem0AndConfirm;
    private readonly InputAction m_OnlyUI_MouseItem1AndConfirm;
    private readonly InputAction m_OnlyUI_MouseMovement;
    public struct OnlyUIActions
    {
        private @InputActions m_Wrapper;
        public OnlyUIActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_OnlyUI_Movement;
        public InputAction @ExtraConfirm => m_Wrapper.m_OnlyUI_ExtraConfirm;
        public InputAction @MouseItem0AndConfirm => m_Wrapper.m_OnlyUI_MouseItem0AndConfirm;
        public InputAction @MouseItem1AndConfirm => m_Wrapper.m_OnlyUI_MouseItem1AndConfirm;
        public InputAction @MouseMovement => m_Wrapper.m_OnlyUI_MouseMovement;
        public InputActionMap Get() { return m_Wrapper.m_OnlyUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnlyUIActions set) { return set.Get(); }
        public void SetCallbacks(IOnlyUIActions instance)
        {
            if (m_Wrapper.m_OnlyUIActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMovement;
                @ExtraConfirm.started -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnExtraConfirm;
                @ExtraConfirm.performed -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnExtraConfirm;
                @ExtraConfirm.canceled -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnExtraConfirm;
                @MouseItem0AndConfirm.started -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseItem0AndConfirm;
                @MouseItem0AndConfirm.performed -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseItem0AndConfirm;
                @MouseItem0AndConfirm.canceled -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseItem0AndConfirm;
                @MouseItem1AndConfirm.started -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseItem1AndConfirm;
                @MouseItem1AndConfirm.performed -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseItem1AndConfirm;
                @MouseItem1AndConfirm.canceled -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseItem1AndConfirm;
                @MouseMovement.started -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.performed -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.canceled -= m_Wrapper.m_OnlyUIActionsCallbackInterface.OnMouseMovement;
            }
            m_Wrapper.m_OnlyUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @ExtraConfirm.started += instance.OnExtraConfirm;
                @ExtraConfirm.performed += instance.OnExtraConfirm;
                @ExtraConfirm.canceled += instance.OnExtraConfirm;
                @MouseItem0AndConfirm.started += instance.OnMouseItem0AndConfirm;
                @MouseItem0AndConfirm.performed += instance.OnMouseItem0AndConfirm;
                @MouseItem0AndConfirm.canceled += instance.OnMouseItem0AndConfirm;
                @MouseItem1AndConfirm.started += instance.OnMouseItem1AndConfirm;
                @MouseItem1AndConfirm.performed += instance.OnMouseItem1AndConfirm;
                @MouseItem1AndConfirm.canceled += instance.OnMouseItem1AndConfirm;
                @MouseMovement.started += instance.OnMouseMovement;
                @MouseMovement.performed += instance.OnMouseMovement;
                @MouseMovement.canceled += instance.OnMouseMovement;
            }
        }
    }
    public OnlyUIActions @OnlyUI => new OnlyUIActions(this);

    // MainMenu
    private readonly InputActionMap m_MainMenu;
    private IMainMenuActions m_MainMenuActionsCallbackInterface;
    private readonly InputAction m_MainMenu_Movement;
    private readonly InputAction m_MainMenu_Press;
    private readonly InputAction m_MainMenu_MouseMovement;
    private readonly InputAction m_MainMenu_AnyKey;
    public struct MainMenuActions
    {
        private @InputActions m_Wrapper;
        public MainMenuActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_MainMenu_Movement;
        public InputAction @Press => m_Wrapper.m_MainMenu_Press;
        public InputAction @MouseMovement => m_Wrapper.m_MainMenu_MouseMovement;
        public InputAction @AnyKey => m_Wrapper.m_MainMenu_AnyKey;
        public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
        public void SetCallbacks(IMainMenuActions instance)
        {
            if (m_Wrapper.m_MainMenuActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMovement;
                @Press.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnPress;
                @Press.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnPress;
                @Press.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnPress;
                @MouseMovement.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMouseMovement;
                @AnyKey.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnAnyKey;
                @AnyKey.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnAnyKey;
                @AnyKey.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnAnyKey;
            }
            m_Wrapper.m_MainMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Press.started += instance.OnPress;
                @Press.performed += instance.OnPress;
                @Press.canceled += instance.OnPress;
                @MouseMovement.started += instance.OnMouseMovement;
                @MouseMovement.performed += instance.OnMouseMovement;
                @MouseMovement.canceled += instance.OnMouseMovement;
                @AnyKey.started += instance.OnAnyKey;
                @AnyKey.performed += instance.OnAnyKey;
                @AnyKey.canceled += instance.OnAnyKey;
            }
        }
    }
    public MainMenuActions @MainMenu => new MainMenuActions(this);
    public interface IAlwaysActiveActions
    {
        void OnToggleInventory(InputAction.CallbackContext context);
        void OnTogglePause(InputAction.CallbackContext context);
        void OnItem0(InputAction.CallbackContext context);
        void OnItem1(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnToggleDebug(InputAction.CallbackContext context);
    }
    public interface IGroundedActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnSword(InputAction.CallbackContext context);
        void OnShield(InputAction.CallbackContext context);
    }
    public interface IOnlyUIActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnExtraConfirm(InputAction.CallbackContext context);
        void OnMouseItem0AndConfirm(InputAction.CallbackContext context);
        void OnMouseItem1AndConfirm(InputAction.CallbackContext context);
        void OnMouseMovement(InputAction.CallbackContext context);
    }
    public interface IMainMenuActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnPress(InputAction.CallbackContext context);
        void OnMouseMovement(InputAction.CallbackContext context);
        void OnAnyKey(InputAction.CallbackContext context);
    }
}
